apiVersion: v1
kind: ConfigMap
metadata:
  name: riocsi-config
  namespace: riocsi
data:
  kubeconfig: |
    container_runtime: containerd
    set_io_limits: true
    read_iops_limit: ["RioVolGroup=30"]
    write_iops_limit: ["RioVolGroup=20"]
    base_iops_limit: ["RioVolGroup=2000"]
    max_iops_limit: ["RioVolGroup=20000"]
    read_bps_limit: ["RioVolGroup=524288"]
    write_bps_limit: ["RioVolGroup=262144"]
    base_bps_limit: ["RioVolGroup=104857600"]
    max_bps_limit: ["RioVolGroup=314572800"]
    metrics_path: /metric
    metrics_addr: 9099
    probe_addr: 9098
    disable_exporter_metrics: false
    iscsi_username: rio-csi
    iscsi_passwd: rio-123