# permissions for end users to edit lvmvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: lvmvolume-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rio-csi
    app.kubernetes.io/part-of: rio-csi
    app.kubernetes.io/managed-by: kustomize
  name: lvmvolume-editor-role
rules:
- apiGroups:
  - qvm.rio-csi.qiniu.io
  resources:
  - lvmvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qvm.rio-csi.qiniu.io
  resources:
  - lvmvolumes/status
  verbs:
  - get
