# permissions for end users to view nodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: node-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: rio-csi
    app.kubernetes.io/part-of: rio-csi
    app.kubernetes.io/managed-by: kustomize
  name: node-viewer-role
rules:
- apiGroups:
  - rio.qiniu.io
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rio.qiniu.io
  resources:
  - nodes/status
  verbs:
  - get
