---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - rio.qiniu.io
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rio.qiniu.io
  resources:
  - volumes/finalizers
  verbs:
  - update
- apiGroups:
  - rio.qiniu.io
  resources:
  - volumes/status
  verbs:
  - get
  - patch
  - update
