resources:
  - namespace.yaml
  - storageclass/storageclass.yaml
  - driver/csi-driver.yaml
  - driver/daemonset.yaml
  - driver/configmap.yaml
  - provisioner/deployment.yaml
  - provisioner/rbac.yaml
  - ../../config/crd