apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: riocsi
    app.kubernetes.io/created-by: rio-csi
    app.kubernetes.io/part-of: rio-csi
  name: riocsi
---